### ISSUE TITLE
Binding to port

### ISSUE THREAD

**Issue by jakeboyles** [kmoe/slack-pokebot#19]
I used the deploy to heroku button and am getting a problem with it not being able to bind to port. Am I missing something?

**Comment by jakeboyles** [comment]
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

**Comment by chris-j-major** [comment]
Hi jakeboyles - I don't think it should bind to a port - it doesn't provide a web interface.

**Comment by jakeboyles** [comment]
I didnt think so either but for some reason its crashing my app on heroku

**Comment by kmoe** [comment]
Ah I had this - are you using a free dyno?

**Comment by kmoe** [comment]
I think there's a problem with Heroku where free dynos for nodejs apps can't be of the `worker` type.

**Comment by kmoe** [comment]
Thanks for bringing this up - I will investigate now.

**Comment by jakeboyles** [comment]
Yeah im using the free dyno. I was just going to wrap an express server around it and keep hitting the route with pingdom...

**Comment by kmoe** [comment]
@jakeboyles yeah I actually considered doing that before I upgraded to a hobby dyno (which I was going to do anyway) - seems wasteful but it genuinely seems to be a Heroku limitation/bug.

**Comment by kmoe** [comment]
If you initialise an express server you won't need to pingdom though

**Comment by kmoe** [comment]
Just having it listening is enough

**Comment by jakeboyles** [comment]
I figured out what to do.
<img width="1298" alt="screen shot 2016-07-28 at 5 17 36 pm" src="https://cloud.githubusercontent.com/assets/2816632/17229783/37d70f2c-54e7-11e6-9fb5-49b6feca574d.png">

**Comment by jakeboyles** [comment]
That solved it. So you can use the free dyno you just need to switch your worker.

**Comment by kmoe** [comment]
Interesting, I didn't have the option to do that when I tried - but I'd accidentally initialised the `Procfile` with only a `web` worker defined so maybe it 'stuck' that way.

**Comment by kmoe** [comment]
Thank you very much for your solution - I'll add it to the README.

**Comment by chris-j-major** [comment]
If it's non-intuitive, perhaps we could put an small express server there - we could even serve up stats from it...

**Comment by kmoe** [comment]
@chris-j-major that's a good extension, especially if paired with a nice frontend
you could even put Niantic server status there!

**Comment by kmoe** [comment]
@jakeboyles let me know if it works now this is resolved!

**Comment by jakeboyles** [comment]
Yeah, its working fine now. I think ill still hit the sleeping issue though.

**Comment by jakeboyles** [comment]
Unless the constant polling of the api solves that, so it might not sleep...

**Comment by kmoe** [comment]
Yeah, I expect you'll just end up using up your free dyno hours while the app is running.
