### ISSUE TITLE
Ensure rare pokemon are alerted

### ISSUE THREAD

**Issue by chris-major-improbable** [kmoe/slack-pokebot#8]
User defined list of rare pokemon, should be always alerted regardless of radius and spam filter.

Some very rare ones might require an @channel or @here alert

**Comment by kmoe** [comment]
we can use this spreadsheet to compile a ranking https://docs.google.com/spreadsheets/d/19KhsaoXlbY1AkcWNs7vCldTvz8OhAXtNCemM0R5Arwo/pubhtml

**Comment by kmoe** [comment]
I propose that we have three classifications:

_Very rare_: notifies `@here` in Slack if Pokemon is within 300m
_Rare_: posts in Slack if Pokemon is within 200m
_Common_: posts in Slack if Pokemon is within 100m and has high IVs

can adjust values of course.

IVs may require a separate FR as I'm not sure how to do that yet.

**Comment by chris-major-improbable** [comment]
Sounds good. But we might need to think how to score IVs effectively.

**Comment by kmoe** [comment]
This should be working now - alas, we haven't had any rare Pokemon around the office 😢
